Repository FastClap/forward-backend, pull requests merged in 2022-12, with the labels that each got.

#1 Docker/tibo
  .gitignore
  apps/app.controller.spec.ts
  apps/app.controller.ts
  apps/app.entity.ts
  apps/app.module.ts
  apps/app.service.ts
  apps/main.ts
  dev/.dockerignore
  dev/Dockerfile
  dev/docker-compose.yml
  dev/env.example
  package.json
  src/app.module.ts
Labels: enhancement

#2 feat(formatter workflow): added a formatter for the apps folder
  .eslintrc.js
  .github/workflows/prettier.yml
Labels: enhancement

#3 Update README project ressource added
  .gitignore
  README.md
  apps/app.controller.ts
  apps/app.module.ts
  apps/app.service.ts
  apps/main.ts
  apps/project/dto/create-project.dto.ts
  apps/project/dto/update-project.dto.ts
  apps/project/project.controller.ts
  apps/project/project.entity.ts
  apps/project/project.module.ts
  apps/project/project.service.ts
  apps/project/test/project.controller.spec.ts
  apps/project/test/project.service.spec.ts
  apps/test/app.controller.spec.ts
  apps/user/user.entity.ts
  dev/Dockerfile
  dev/docker-compose.yml
  dev/env.example
  package-lock.json
  package.json
  test/app.e2e-spec.ts
  test/jest-e2e.json
Labels: enhancement

#8 feat(sequence App): added sequence Entity with all the routes and services (including dto and modules) to handle manipulation of a sequence
  apps/app.module.ts
  apps/project/project.module.ts
  apps/project/project.service.ts
  apps/sequence/dto/create-sequence.dto.ts
  apps/sequence/dto/update-sequence.dto.ts
  apps/sequence/sequence.controller.ts
  apps/sequence/sequence.entity.ts
  apps/sequence/sequence.module.ts
  apps/sequence/sequence.service.ts
Labels: enhancement

#10 Add verification for category and tag entities of the projectId if it exists and if it is a UUID
  apps/category/category.controller.ts
  apps/category/category.entity.ts
  apps/category/category.module.ts
  apps/category/category.service.ts
  apps/category/dto/create-category.dto.ts
  apps/tag/dto/create-tag.dto.ts
  apps/tag/tag.module.ts
  apps/tag/tag.service.ts
Labels: enhancement

#11 Fix project error/tibo
  apps/project/project.service.ts
  apps/project/test/project.controller.spec.ts
  apps/project/test/project.service.spec.ts
  apps/tag/tag.service.ts
Labels: bug

#12 Refactor api endpoints/tibo
  apps/category/category.controller.ts
  apps/category/category.entity.ts
  apps/category/category.module.ts
  apps/category/category.service.ts
  apps/category/dto/create-category.dto.ts
  apps/category/dto/update-category.dto.ts
  apps/file/file.upload.controller.ts
  apps/file/file.upload.module.ts
  apps/file/file.upload.service.ts
  apps/file/file.upload.utils.ts
  apps/form/comedian/dto/create-form-comedian.dto.ts
  apps/form/comedian/dto/update-form-comedian.dto.ts
  apps/form/comedian/form.comedian.controller.ts
  apps/form/comedian/form.comedian.entity.ts
  apps/form/comedian/form.comedian.module.ts
  apps/form/comedian/form.comedian.service.ts
  apps/form/dto/create-form.dto.ts
  apps/form/dto/update-form.dto.ts
  apps/form/form.controller.ts
  apps/form/form.entity.ts
  apps/form/form.module.ts
  apps/form/place/dto/create-form-place.dto.ts
  apps/form/place/dto/update-form-place.dto.ts
  apps/form/place/form.place.controller.ts
  apps/form/place/form.place.entity.ts
  apps/form/place/form.place.module.ts
  apps/form/place/form.place.service.ts
  apps/project/dto/create-project.dto.ts
  apps/project/dto/update-project.dto.ts
  apps/project/project.controller.ts
  apps/project/project.entity.ts
  apps/project/project.service.ts
  apps/sequence/dto/create-sequence.dto.ts
  apps/sequence/dto/update-sequence.dto.ts
  apps/sequence/sequence.controller.ts
  apps/sequence/sequence.entity.ts
  apps/sequence/sequence.module.ts
  apps/sequence/sequence.service.ts
  apps/tag/dto/create-tag.dto.ts
  apps/tag/dto/update-tag.dto.ts
  apps/tag/tag.controller.ts
  apps/tag/tag.entity.ts
  apps/tag/tag.module.ts
  apps/tag/tag.service.ts
Labels: enhancement

#14 feat(tag entity): changed automatically generated primary key to primarykey sent in body to handle tag id from frontend
  apps/tag/dto/create-tag.dto.ts
  apps/tag/dto/update-tag.dto.ts
  apps/tag/tag.entity.ts
  apps/tag/tag.service.ts
Labels: enhancement

#17 Libraries/gurvan
  apps/category/category.controller.ts
  apps/category/category.service.ts
  apps/form/comedian/form.comedian.controller.ts
  apps/form/comedian/form.comedian.service.ts
  apps/form/form.controller.ts
  apps/form/form.service.ts
  apps/form/place/form.place.controller.ts
  apps/form/place/form.place.service.ts
  apps/project/project.controller.ts
  apps/project/project.service.ts
  apps/sequence/sequence.controller.ts
  apps/sequence/sequence.service.ts
  apps/tag/tag.controller.ts
  apps/tag/tag.module.ts
  apps/tag/tag.service.ts
  apps/utils/decorators/Is-uuid-param.decorator.ts
  apps/utils/exceptions/bad-request.exception.ts
  apps/utils/exceptions/not-found.exception.ts
Labels: enhancement

#18 feat(sequence name already exist): added verification when create sequence to check if sequence name already exists and added exception function in utils to throw when conflict or if already exist
  apps/category/category.service.ts
  apps/sequence/sequence.service.ts
  apps/tag/tag.service.ts
  apps/utils/exceptions/conflict.exception.ts
Labels: enhancement

#19 feat(project metadata): added metadata field in project entity filled when a tag is added in the project
  apps/project/project.controller.ts
  apps/project/project.entity.ts
  apps/project/project.service.ts
  apps/tag/dto/create-tag.dto.ts
  apps/tag/tag.service.ts
Labels: enhancement

#22 feat(project): add fake subscriber that creating 3 categories and 1 sequence at the project creation
  apps/app.module.ts
  apps/project/project.module.ts
  apps/project/project.service.ts
  apps/project/subscribers/create-project.subscriber.ts
Labels: enhancement

#24 feat(swagger): add Swagger Documentation to the API with Tags with README updated
  README.md
  apps/app.controller.ts
  apps/category/category.controller.ts
  apps/form/form.controller.ts
  apps/main.ts
  apps/project/project.controller.ts
  apps/sequence/sequence.controller.ts
  apps/tag/tag.controller.ts
  package.json
Labels: documentation, enhancement
